### ISSUE TITLE
Column name

### ISSUE THREAD

**Issue by apopova-cartera** [minibo29/epam-hm#9]
https://github.com/minibo29/epam-hm/blob/5e368b159ebbf6a70869bf131ab2cbd8ce5415f8/src/sql_basics/steps_2-5.sql#L37

It's better to name this column user_id

**Comment by minibo29** [comment]
No no no...))
in this table,  we can also add column 'corespondented_by'....
also, we have a pattern like DDD(if I correctly understand this pattern..)
